# Generated by Django 5.0.4 on 2024-04-15 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('cor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField()),
                ('vencimento', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.categoria')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.meta')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField()),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.despesa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='meta',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.pessoa'),
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pessoas', models.ManyToManyField(to='source.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='meta',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.propriedade'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='propriedade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.propriedade'),
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data', models.DateField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.pessoa')),
            ],
        ),
    ]
