# Generated by Django 5.0.4 on 2024-04-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
