# Generated by Django 5.0.4 on 2024-05-18 15:18

import source.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_alter_despesa_vencimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='propriedade',
            name='descricao',
            field=models.TextField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='propriedade',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
