# Generated by Django 5.0.4 on 2024-05-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_alter_propriedade_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesa',
            old_name='data',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='despesa',
            old_name='vencimento',
            new_name='data_pagamento',
        ),
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='renda',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
