# Generated by Django 5.0.4 on 2024-05-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_rename_data_despesa_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_criacao',
            field=models.DateField(verbose_name='criacao'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='vencimento'),
        ),
    ]
