# Generated by Django 5.0.4 on 2024-05-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0010_alter_despesa_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
