# Generated by Django 5.0.4 on 2024-06-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0011_alter_despesa_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('PX', 'PIX'), ('CA', 'Cartão Alimentação'), ('DI', 'Dinheiro')], default='CC', max_length=2),
            preserve_default=False,
        ),
    ]
