# Generated by Django 5.0.4 on 2024-06-05 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0012_pagamento_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='data_pagamento',
        ),
    ]
