# Generated by Django 5.0.4 on 2024-06-16 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0013_remove_despesa_data_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField()),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='source.propriedade')),
            ],
        ),
        migrations.AddField(
            model_name='despesa',
            name='parcelamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='source.parcelamento'),
        ),
    ]
